<h2>Products Display!</h2>
<br><br>

<?php


if ($products->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Product Name</th>
            <th>Description</th>
            <th>Tags</th>
            <th>Price</th>
            <th>Stock</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="6">Users quantity: <?php echo $products->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($products as $product) { ?>
            <tr>
                <td><?php echo $product->product_id; ?></td>
                <td><?php echo $product->product_name; ?></td>
                <td><?php echo $product->description; ?></td>
                <td><?php echo $product->tags; ?></td>
                <td><?php echo $product->price; ?></td>
                <td><?php echo $product->stock; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
