<h2>Product add</h2>

<?php echo $this->tag->form("product/addProduct"); ?>  <!-- OR just use "product/add" -->

    <p>
        <label for="product_name">Product Name</label>
        <?php echo $this->tag->textField("product_name"); ?>
    </p>

    <p>
        <label for="description">Description</label>
        <?php echo $this->tag->textArea(["description", 'cols' => 40, 'rows' => 3]); ?>
    </p>

    <p>
        <label for="tags">Tags</label>
        <?php echo $this->tag->textField("tags"); ?>
    </p>

    <p>
        <label for="price">Price</label>
        <?php echo $this->tag->textField("price"); ?>
    </p>

    <p>
        <label for="stock">Stock</label>
        <?php echo $this->tag->textField("stock"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Add Product"); ?>
    </p>

</form>