<?php

echo "<h1>Events Task</h1>";

echo PHP_EOL;       // php End Of Line...

echo $this->tag->linkTo(
    [
        'product',
        'Add Product',
        'class' => 'btn btn-primary'
    ]
    
);

echo '<br><br>';

echo $this->tag->linkTo(
    [
        'displayProducts',
        'Display Products',
        'class' => 'btn btn-info'
    ]
    
);

echo '<br><br>';

echo $this->tag->linkTo(
    [
        'order',
        'Add Order',
        'class' => 'btn btn-primary'
    ]
    
);

echo '<br><br>';

echo $this->tag->linkTo(
    [
        'displayOrders',
        'Display Orders',
        'class' => 'btn btn-info'
    ]
    
);

echo '<br><br>';

echo $this->tag->linkTo(
    [
        'settings',
        'Settings',
        'class' => 'btn btn-secondary'
    ]
    
);

echo '<br><br>';



// if ($users->count() > 0) {
    ?>
    <!-- <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php //echo $users->count(); ?></td>
        </tr>
        </tfoot>
        <tbody> -->
        <?php // foreach ($users as $user) { ?>
            <!-- <tr>
                <td><?php // echo $user->id; ?></td>
                <td><?php // echo $user->name; ?></td>
                <td><?php // echo $user->email; ?></td>
            </tr> -->
        <?php // } ?>
        <!-- </tbody>
    </table> -->
    <?php
// }
