


<?php
// echo "orders Display";
if ($orders->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Customer Name</th>
            <th>Customer Address</th>
            <th>Zipcode</th>
            <th>Product</th>
            <th>Quantity</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="6">Orders quantity: <?php echo $orders->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($orders as $order) { ?>
            <tr>
                <td><?php echo $order->order_id; ?></td>
                <td><?php echo $order->customer_name; ?></td>
                <td><?php echo $order->customer_address; ?></td>
                <td><?php echo $order->zipcode; ?></td>
                <td><?php echo $order->product; ?></td>
                <td><?php echo $order->quantity; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
